library(ggplot2)
####################################################################
#geometry, a matrix containing the cartesian coordinates of each bin in three dimensional space.
# use geometry file on github: https://github.com/rajewsky-lab/distmap 
geometry=read.delim('DVEX/geometry_3039.txt',
                    header = TRUE,sep=' ')
dim(geometry) #3039 bin x 3 coords (the as insitu.matrix)
geometry[1:3,1:3]
geometry=as.matrix(geometry)

locations=read.table('novosparc/tissue.locaitons_3039xzcoords.txt')
dim(locations)
head(geometry[,c(1,3)])
head(locations) #all match

####################################################################
## read in cell mapping probablity generated by novosparc
mcc=read.table('novosparc/tissue.gw_1297gene_3039bin.txt',as.is=T)
dim(mcc) #1297 cells x 3039 bins

mcc=t(mcc)
dim(mcc) #3039 bin x 1297 cell
mcc[1:3,1:3]
apply(mcc,2,sum) #sum.prob per cell
apply(mcc,1,sum) #sum.prob per bin


## compare the two cell assigning matrix
novo.mcc=mcc;

distmap.mcc=as.matrix(data.table::fread('distmap.mcc.txt'))
novo.mcc[1:3,1:3]
distmap.mcc[1:3,1:3]

## compare Distmap and Novosparc
plot(novo.mcc[,1],distmap.mcc[,1])
all.cor.values=sapply(1:ncol(distmap.mcc),function(i){
  cor(distmap.mcc[,i],novo.mcc[,i],method = 'spearman')
})
summary(all.cor.values)
hist(all.cor.values)

