
library(ggplot2)
library(Seurat)
library(gridExtra)
library(tidyverse)
library(rsample)      # data splitting 
library(randomForest) # basic implementation
library(ranger)       # a faster implementation of randomForest
library(caret)        # an aggregator package for performing many machine learning models
library(h2o)          # an extremely fast java-based platform
library(multiclassPairs)
########################################################
## read in gene chro info
df.gene.table=data.table::fread('../../single.cell_datasets/embryo_germline/gene.meta_embryo.txt',header=T,sep='\t')
head(df.gene.table)
df.gene.table=df.gene.table[df.gene.table$LOCATION_ARM %in% c('2R','3R','3L','4','2L','X','Y'),]
table(df.gene.table$LOCATION_ARM)

df.gene.table=as.data.frame(df.gene.table)
#rownames(df.gene.table)=df.gene.table$current_symbol
rownames(df.gene.table)=df.gene.table$FBID_KEY

########################################################################################
## read in gene expression data and sample meta information 

dat.both=readRDS('../../single.cell_sex.differences/embryo_sex.cells/integrated.sexed.samples_seurat.obj.rds')
grep("Sxl|msl-2",rownames(dat.both))

dim(dat.both) #12185 x 17142
sum(rownames(dat.both) %in% df.gene.table$submitted_item)#11740
dat.both=dat.both[rownames(dat.both) %in% df.gene.table$submitted_item,]

i=match(rownames(dat.both),df.gene.table$submitted_item)
sum(df.gene.table[i,]$submitted_item==rownames(dat.both)) #11740

expr.mat=as.matrix(dat.both@assays$RNA@counts)
rownames(expr.mat)=df.gene.table[i,]$validated_id #for ranger to tolerate feature names

sample.meta=dat.both@meta.data

dim(expr.mat) # 11740 gene X 17142cell
dim(sample.meta) #17142cell  4
head(sample.meta)
sample.meta0=sample.meta;

## filter out low expressed genes: express in 5% cells
i=Matrix::rowSums(expr.mat>0)
input.dat0=expr.mat[i>ncol(expr.mat)*0.05,]
features=rownames(input.dat0)
dim(input.dat0) #6073 17142

dim(input.dat0)
dim(sample.meta0)
table(sample.meta0$sex)

##########################################################################
## https://github.com/NourMarzouka/multiclassPairs/blob/master/README.md
library(multiclassPairs)

# split the data
# 60% as training data and 40% as testing data
input.dat=input.dat0;
sample.meta=sample.meta0;
if(F){
  n <- ncol(input.dat0)
  set.seed(2124)
  pick=sample(1:n,size=5000,replace = F)
  input.dat=input.dat0[,pick]
  sample.meta=sample.meta0[pick,]
  table(sample.meta$sex)
}

set.seed(321)
split = caTools::sample.split(sample.meta$sex, SplitRatio = 0.8)
table(sample.meta[split,]$sex) #8309         5405 
table(sample.meta[!split,]$sex) #2077         1351 

train <- input.dat[,split]
test  <- input.dat[,!split]
train.meta <- sample.meta[split,]
test.meta <- sample.meta[!split,]
table(train.meta$sex)
table(test.meta$sex)

# create data object 
object <- ReadData(#Data = expr.mat,
                   #Labels=sample.meta$sex,
                   Data = train,
                   Labels = train.meta$sex,
                   verbose = FALSE)
object

#########################################################
## data-driven filter genes
n.gene=nrow(train)
if(!file.exists('sc_classifier_filtered_genes.rds')){
  system.time(
    filtered_genes <- filter_genes_TSP(data_object = object,
                                     filter = "one_vs_one",
                                     platform_wise = FALSE,
                                     featureNo = n.gene,
                                     UpDown = TRUE,
                                     verbose = TRUE)
  )
  #filtered_genes
  saveRDS(filtered_genes,'sc_classifier_filtered_genes.rds') #6k gene, 20min
}
length(filtered_genes$OnevsrestScheme$filtered_genes$embryoFemale)
length(filtered_genes$OnevsrestScheme$filtered_genes$embryoMale)

#########################################################
## use prior gene set
# using the object that is generated by ReadData
# we can create genes object with all genes to skip filtering step
if(F){
  # Get the class names
  classes <- unique(object$data$Labels)
  
  # create empty genes object
  genes_all <- list(OnevsrestScheme = list(filtered_genes = NULL,
                                           calls = c()))
  class(genes_all) <- "OnevsrestScheme_genes_TSP"
  
  # prepare the slots for each class
  tmp <- vector("list", length(classes))
  names(tmp) <- classes
  
  genes_all$OnevsrestScheme$filtered_genes <- tmp
  genes_all$OnevsrestScheme$calls <- c()
  genes_all
  
  # fill the gene object in each slot
  prior.genes=rownames(object$data$Data)[grep('Sxl|roX|mle|mof|msl',rownames(object$data$Data))]
  prior.genes
  for (i in classes) {
    #genes_all$OnevsrestScheme$filtered_genes[[i]] <- rownames(object$data$Data)
    genes_all$OnevsrestScheme$filtered_genes[[i]] <- prior.genes
  }
  
  # This is the gene object with all genes
  genes_all
  filtered_genes=genes_all
}

#####################################################
# Let's train our model
if(!file.exists('classifier_train80.rds')){
  system.time(classifier <- train_one_vs_rest_TSP(data_object = object,
                                      filtered_genes = filtered_genes,
                                      k_range = 2:1000,
                                      include_pivot = FALSE,
                                      one_vs_one_scores = TRUE,
                                      platform_wise_scores = FALSE,
                                      seed = 1234,
                                      verbose = FALSE)
  )
  saveRDS(classifier,'sc_classifier_train80.rds') #12hr
}
classifier #female 7 rules, male 267 rules.
classifier$classifiers
classifier$classifiers$embryoFemale
classifier$classifiers$embryoMale$TSPs
names(classifier$classifiers)
i=grep('FBgn0264270',rownames(classifier$classifiers$embryoMale$TSPs))
classifier$classifiers$embryoMale$TSPs[i,]

# apply on the training data
# To have the classes in output in specific order, we can use classes argument
results_train <- predict_one_vs_rest_TSP(classifier = classifier,
                                         Data = object,
                                         tolerate_missed_genes = TRUE,
                                         weighted_votes = TRUE,
                                         classes = c("embryoFemale",'embryoMale'),
                                         verbose = TRUE)

# apply on the testing data
results_test <- predict_one_vs_rest_TSP(classifier = classifier,
                                        Data = test,
                                        tolerate_missed_genes = TRUE,
                                        weighted_votes = TRUE,
                                        classes = c("embryoFemale",'embryoMale'),
                                        verbose = TRUE)

# get a look over the scores in the testing data
knitr::kable(head(results_train))
table(results_train$max_score)

knitr::kable(head(results_test))
table(results_test$max_score)

head(results_test) #a data frame with probs

# Confusion Matrix and Statistics on training data
caret::confusionMatrix(data = factor(results_train$max_score, 
                                     levels = unique(object$data$Labels)),
                       reference = factor(object$data$Labels, 
                                          levels = unique(object$data$Labels)),
                       mode="everything")

# Confusion Matrix and Statistics on testing data
caret::confusionMatrix(data = factor(results_test$max_score, 
                                     levels = unique(object$data$Labels)),
                       reference = factor(test.meta$sex,
                                          levels = unique(object$data$Labels)),
                       mode="everything")


if(F){
  # Visualiation
  # plot for the rules and scores in the training data
  pdf("TSP_out.pdf")
  plot_binary_TSP(Data = object, # we are using the data object here
                  classifier = classifier, 
                  prediction = results_train, 
                  classes = c("embryoFemale",'embryoMale'),
                  margin = c(0,5,0,10),
                  title = "Training data")
  
  # plot for the rules and scores in the testing data
  plot_binary_TSP(Data = test, # ExpressionSet
                  ref = test.meta$sex,
                  classifier = classifier, 
                  prediction = results_test, 
                  classes =  c("F",'M'),
                  title = "Testing data",
                  margin = c(0,5,0,10))
  dev.off()
}


